"""
清算瀑布收割策略 — 配置参数
Binance USDⓈ-M (U 本位) — 适配 2026 WebSocket 新架构
小账户模式: 1 USDC / 20x 杠杆
"""

from typing import List

# ============================================================
# 交易对 (仅保留 1USDC 可交易的)
# SOL: 最小 0.1 SOL ≈ $9.50 名义 → 保证金 $0.48 @20x ✅
# ============================================================
SYMBOLS: List[str] = [
    "ETHUSDT",
    "BCHUSDT",
    "XRPUSDT",
    "LTCUSDT",
    "TRXUSDT",
    "ETCUSDT",
    "LINKUSDT",
    "XLMUSDT",
    "ADAUSDT",
    "XMRUSDT",
    "DASHUSDT",
    "ZECUSDT",
    "XTZUSDT",
    "BNBUSDT",
    "ATOMUSDT",
    "ONTUSDT",
    "IOTAUSDT",
    "BATUSDT",
    "VETUSDT",
    "NEOUSDT",
    "QTUMUSDT",
    "IOSTUSDT",
    "THETAUSDT",
    "ALGOUSDT",
    "ZILUSDT",
    "KNCUSDT",
    "ZRXUSDT",
    "COMPUSDT",
    "DOGEUSDT",
    "KAVAUSDT",
    "BANDUSDT",
    "RLCUSDT",
    "SNXUSDT",
    "DOTUSDT",
    "YFIUSDT",
    "CRVUSDT",
    "TRBUSDT",
    "RUNEUSDT",
    "SUSHIUSDT",
    "EGLDUSDT",
    "SOLUSDT",
    "ICXUSDT",
    "STORJUSDT",
    "UNIUSDT",
    "AVAXUSDT",
    "ENJUSDT",
    "KSMUSDT",
    "NEARUSDT",
    "AAVEUSDT",
    "FILUSDT",
    "RSRUSDT",
    "BELUSDT",
    "AXSUSDT",
    "ZENUSDT",
    "SKLUSDT",
    "GRTUSDT",
    "1INCHUSDT",
    "CHZUSDT",
    "SANDUSDT",
    "ANKRUSDT",
    "RVNUSDT",
    "SFPUSDT",
    "COTIUSDT",
    "CHRUSDT",
    "MANAUSDT",
    "ALICEUSDT",
    "HBARUSDT",
    "ONEUSDT",
    "CELRUSDT",
    "HOTUSDT",
    "MTLUSDT",
    "OGNUSDT",
    "1000SHIBUSDT",
    "GTCUSDT",
    "BTCDOMUSDT",
    "IOTXUSDT",
    "C98USDT",
    "MASKUSDT",
    "ATAUSDT",
    "DYDXUSDT",
    "1000XECUSDT",
    "GALAUSDT",
    "CELOUSDT",
    "ARUSDT",
    "ARPAUSDT",
    "CTSIUSDT",
    "LPTUSDT",
    "ENSUSDT",
    "PEOPLEUSDT",
    "ROSEUSDT",
    "DUSKUSDT",
    "FLOWUSDT",
    "IMXUSDT",
    "API3USDT",
    "GMTUSDT",
    "APEUSDT",
    "WOOUSDT",
    "JASMYUSDT",
    "OPUSDT",
    "INJUSDT",
    "STGUSDT",
    "SPELLUSDT",
    "1000LUNCUSDT",
    "LUNA2USDT",
    "LDOUSDT",
    "ICPUSDT",
    "APTUSDT",
    "QNTUSDT",
    "FETUSDT",
    "MAGICUSDT",
    "TUSDT",
    "HIGHUSDT",
    "MINAUSDT",
    "ASTRUSDT",
    "PHBUSDT",
    "GMXUSDT",
    "CFXUSDT",
    "STXUSDT",
    "ACHUSDT",
    "SSVUSDT",
    "CKBUSDT",
    "LQTYUSDT",
    "USDCUSDT",
    "IDUSDT",
    "ARBUSDT",
    "JOEUSDT",
    "TLMUSDT",
    "HFTUSDT",
    "XVSUSDT",
    "BLURUSDT",
    "EDUUSDT",
    "SUIUSDT",
    "1000PEPEUSDT",
    "1000FLOKIUSDT",
    "UMAUSDT",
    "NMRUSDT",
    "MAVUSDT",
    "XVGUSDT",
    "WLDUSDT",
    "PENDLEUSDT",
    "ARKMUSDT",
    "AGLDUSDT",
    "YGGUSDT",
    "DODOXUSDT",
    "BNTUSDT",
    "SEIUSDT",
    "CYBERUSDT",
    "ARKUSDT",
    "BICOUSDT",
    "BIGTIMEUSDT",
    "WAXPUSDT",
    "BSVUSDT",
    "RIFUSDT",
    "POLYXUSDT",
    "GASUSDT",
    "POWRUSDT",
    "TIAUSDT",
    "CAKEUSDT",
    "MEMEUSDT",
    "TWTUSDT",
    "ORDIUSDT",
    "STEEMUSDT",
    "ILVUSDT",
    "KASUSDT",
    "BEAMXUSDT",
    "1000BONKUSDT",
    "PYTHUSDT",
    "SUPERUSDT",
    "USTCUSDT",
    "ONGUSDT",
    "ETHWUSDT",
    "JTOUSDT",
    "1000SATSUSDT",
    "AUCTIONUSDT",
    "1000RATSUSDT",
    "ACEUSDT",
    "MOVRUSDT",
    "NFPUSDT",
    "XAIUSDT",
    "WIFUSDT",
    "MANTAUSDT",
    "ONDOUSDT",
    "LSKUSDT",
    "ALTUSDT",
    "JUPUSDT",
    "ZETAUSDT",
    "RONINUSDT",
    "DYMUSDT",
    "PIXELUSDT",
    "STRKUSDT",
    "GLMUSDT",
    "PORTALUSDT",
    "TONUSDT",
    "AXLUSDT",
    "METISUSDT",
    "AEVOUSDT",
    "VANRYUSDT",
    "BOMEUSDT",
    "ETHFIUSDT",
    "ENAUSDT",
    "WUSDT",
    "TNSRUSDT",
    "SAGAUSDT",
    "TAOUSDT",
    "REZUSDT",
    "BBUSDT",
    "NOTUSDT",
    "TURBOUSDT",
    "IOUSDT",
    "ZKUSDT",
    "MEWUSDT",
    "LISTAUSDT",
    "ZROUSDT",
    "RENDERUSDT",
    "BANANAUSDT",
    "RAREUSDT",
    "GUSDT",
    "SYNUSDT",
    "SYSUSDT",
    "BRETTUSDT",
    "POPCATUSDT",
    "SUNUSDT",
    "DOGSUSDT",
    "MBOXUSDT",
    "FLUXUSDT",
    "RPLUSDT",
    "POLUSDT",
    "1MBABYDOGEUSDT",
    "NEIROUSDT",
    "FIDAUSDT",
    "CATIUSDT",
    "HMSTRUSDT",
    "COSUSDT",
    "EIGENUSDT",
    "DIAUSDT",
    "1000CATUSDT",
    "SCRUSDT",
    "GOATUSDT",
    "MOODENGUSDT",
    "SAFEUSDT",
    "SANTOSUSDT",
    "COWUSDT",
    "CETUSUSDT",
    "1000000MOGUSDT",
    "GRASSUSDT",
    "DRIFTUSDT",
    "ACTUSDT",
    "PNUTUSDT",
    "BANUSDT",
    "AKTUSDT",
    "SCRTUSDT",
    "1000CHEEMSUSDT",
    "THEUSDT",
    "MORPHOUSDT",
    "CHILLGUYUSDT",
    "KAIAUSDT",
    "AEROUSDT",
    "ACXUSDT",
    "ORCAUSDT",
    "MOVEUSDT",
    "RAYSOLUSDT",
    "KOMAUSDT",
    "VIRTUALUSDT",
    "SPXUSDT",
    "MEUSDT",
    "AVAUSDT",
    "VELODROMEUSDT",
    "MOCAUSDT",
    "VANAUSDT",
    "PENGUUSDT",
    "LUMIAUSDT",
    "USUALUSDT",
    "AIXBTUSDT",
    "FARTCOINUSDT",
    "KMNOUSDT",
    "CGPTUSDT",
    "HIVEUSDT",
    "DEXEUSDT",
    "PHAUSDT",
    "GRIFFAINUSDT",
    "ZEREBROUSDT",
    "BIOUSDT",
    "COOKIEUSDT",
    "ALCHUSDT",
    "SWARMSUSDT",
    "SONICUSDT",
    "DUSDT",
    "PROMUSDT",
    "SUSDT",
    "SOLVUSDT",
    "ARCUSDT",
    "AVAAIUSDT",
    "TRUMPUSDT",
    "MELANIAUSDT",
    "VTHOUSDT",
    "ANIMEUSDT",
    "PIPPINUSDT",
    "VVVUSDT",
    "BERAUSDT",
    "TSTUSDT",
    "LAYERUSDT",
    "HEIUSDT",
    "IPUSDT",
    "GPSUSDT",
    "SHELLUSDT",
    "KAITOUSDT",
    "REDUSDT",
    "VICUSDT",
    "EPICUSDT",
    "BMTUSDT",
    "MUBARAKUSDT",
    "FORMUSDT",
    "TUTUSDT",
    "BROCCOLI714USDT",
    "BROCCOLIF3BUSDT",
    "SIRENUSDT",
    "BANANAS31USDT",
    "BRUSDT",
    "PLUMEUSDT",
    "NILUSDT",
    "PARTIUSDT",
    "JELLYJELLYUSDT",
    "MAVIAUSDT",
    "PAXGUSDT",
    "WALUSDT",
    "MLNUSDT",
    "GUNUSDT",
    "ATHUSDT",
    "BABYUSDT",
    "PROMPTUSDT",
    "STOUSDT",
    "FHEUSDT",
    "KERNELUSDT",
    "WCTUSDT",
    "INITUSDT",
    "AERGOUSDT",
    "BANKUSDT",
    "DEEPUSDT",
    "HYPERUSDT",
    "JSTUSDT",
    "SIGNUSDT",
    "PUNDIXUSDT",
    "CTKUSDT",
    "AIOTUSDT",
    "DOLOUSDT",
    "HAEDALUSDT",
    "SXTUSDT",
    "ASRUSDT",
    "ALPINEUSDT",
    "B2USDT",
    "SYRUPUSDT",
    "DOODUSDT",
    "OGUSDT",
    "SKYAIUSDT",
    "NXPCUSDT",
    "CVCUSDT",
    "AGTUSDT",
    "AWEUSDT",
    "BUSDT",
    "SOONUSDT",
    "HUMAUSDT",
    "AUSDT",
    "SOPHUSDT",
    "MERLUSDT",
    "HYPEUSDT",
    "1000000BOBUSDT",
    "LAUSDT",
    "HOMEUSDT",
    "RESOLVUSDT",
    "TAIKOUSDT",
    "SQDUSDT",
    "PUMPBTCUSDT",
    "SPKUSDT",
    "MYXUSDT",
    "FUSDT",
    "NEWTUSDT",
    "HUSDT",
    "SAHARAUSDT",
    "ICNTUSDT",
    "BULLAUSDT",
    "IDOLUSDT",
    "MUSDT",
    "PUMPUSDT",
    "CROSSUSDT",
    "AINUSDT",
    "CUSDT",
    "VELVETUSDT",
    "TACUSDT",
    "ERAUSDT",
    "TAUSDT",
    "CVXUSDT",
    "SLPUSDT",
    "ZORAUSDT",
    "TAGUSDT",
    "ESPORTSUSDT",
    "TREEUSDT",
    "PLAYUSDT",
    "NAORISUSDT",
    "TOWNSUSDT",
    "PROVEUSDT",
    "ALLUSDT",
    "INUSDT",
    "CARVUSDT",
    "AIOUSDT",
    "XNYUSDT",
    "USELESSUSDT",
    "SAPIENUSDT",
    "XPLUSDT",
    "WLFIUSDT",
    "SOMIUSDT",
    "BASUSDT",
    "BTRUSDT",
    "MITOUSDT",
    "HEMIUSDT",
    "LINEAUSDT",
    "QUSDT",
    "ARIAUSDT",
    "TAKEUSDT",
    "PTBUSDT",
    "OPENUSDT",
    "FLOCKUSDT",
    "SKYUSDT",
    "AVNTUSDT",
    "HOLOUSDT",
    "XPINUSDT",
    "UBUSDT",
    "ZKCUSDT",
    "TOSHIUSDT",
    "STBLUSDT",
    "0GUSDT",
    "BARDUSDT",
    "ASTERUSDT",
    "TRADOORUSDT",
    "BLESSUSDT",
    "FLUIDUSDT",
    "COAIUSDT",
    "HANAUSDT",
    "MIRAUSDT",
    "AKEUSDT",
    "ORDERUSDT",
    "LIGHTUSDT",
    "XANUSDT",
    "FFUSDT",
    "EDENUSDT",
    "NOMUSDT",
    "TRUTHUSDT",
    "2ZUSDT",
    "EVAAUSDT",
    "LYNUSDT",
    "KGENUSDT",
    "4USDT",
    "GIGGLEUSDT",
    "MONUSDT",
    "YBUSDT",
    "METUSDT",
    "EULUSDT",
    "ENSOUSDT",
    "CLOUSDT",
    "RECALLUSDT",
    "ZBTUSDT",
    "LABUSDT",
    "RIVERUSDT",
    "币安人生USDT",
    "BLUAIUSDT",
    "TURTLEUSDT",
    "APRUSDT",
    "ONUSDT",
    "KITEUSDT",
    "ATUSDT",
    "CCUSDT",
    "MMTUSDT",
    "TRUSTUSDT",
    "UAIUSDT",
    "FOLKSUSDT",
    "STABLEUSDT",
    "JCTUSDT",
    "ALLOUSDT",
    "CLANKERUSDT",
    "BEATUSDT",
    "PIEVERSEUSDT",
    "SENTUSDT",
    "IRYSUSDT",
    "POWERUSDT",
    "WETUSDT",
    "NIGHTUSDT",
    "USUSDT",
    "CYSUSDT",
    "RAVEUSDT",
    "ZKPUSDT",
    "GUAUSDT",
    "LITUSDT",
    "BREVUSDT",
    "COLLECTUSDT",
    "MAGMAUSDT",
    "ZAMAUSDT",
    "FOGOUSDT",
    "FRAXUSDT",
    "SPORTFUNUSDT",
    "AIAUSDT",
    "ACUUSDT",
    "我踏马来了USDT",
    "ELSAUSDT",
    "SKRUSDT",
    "SPACEUSDT",
    "FIGHTUSDT",
    "BIRBUSDT",
    "GWEIUSDT",
    "MEGAUSDT",
    "INXUSDT",
    "TRIAUSDT",
    "ESPUSDT",
    "AZTECUSDT",
    "OPNUSDT",
    "ROBOUSDT",
    "KATUSDT",
    "MANTRAUSDT",
    "龙虾USDT",
    "CFGUSDT",
    "EDGEUSDT",
    "BSBUSDT",
    "XAUTUSDT",
    "BASEDUSDT",
    "PRLUSDT",
    "GENIUSUSDT",
    "CHIPUSDT",
    "OPGUSDT",
    "AIGENSYNUSDT",
    "BILLUSDT",
]

# ============================================================
# 杠杆
# ============================================================
LEVERAGE = 20                           # 全仓杠杆倍数
MARGIN_MODE = "CROSSED"                 # CROSSED | ISOLATED (全仓/逐仓)

# ============================================================
# 清算信号阈值
# ============================================================
LIQUIDATION_THRESHOLD = 20_000          # 清算金额阈值 (USDT)
LIQUIDATION_WINDOW_SEC = 120            # 清算累计窗口 (秒)，更长窗口积累更多清算
MIN_LIQUIDATION_COUNT = 1               # 窗口内最少清算笔数

# ============================================================
# 订单簿信号阈值
# ============================================================
DEPTH_IMBALANCE_RATIO = 1.1             # 买卖深度比阈值
DEPTH_CHECK_LEVELS = 10                 # 取前 N 档深度
MIN_DEPTH_USDT = 2_000                  # 单侧最低深度 (USDT)

# ============================================================
# VWAP 偏离阈值
# ============================================================
VWAP_DEVIATION = 0.005                  # 价格偏离 VWAP 0.5% 以上
VWAP_PERIOD_MINUTES = 30                # VWAP 计算周期 (分钟)

# ============================================================
# 入场参数
# ============================================================
ENTRY_OFFSET_PCT = 0.001                # 限价单偏离当前价 0.1%
ENTRY_TIMEOUT_SEC = 10                  # 限价单超时 (秒)

# ============================================================
# 出场参数
# ============================================================
TAKE_PROFIT_PCT = 0.008                 # 止盈 0.8%
STOP_LOSS_PCT = 0.010                   # 止损 1.0%
MAX_HOLDING_SEC = 300                   # 最大持仓 5 分钟
VWAP_REVERSION_PCT = 0.001              # VWAP 回归 0.1% 以内出场
MAKER_FEE = 0.0002                      # Maker 费率 0.02%
TAKER_FEE = 0.0005                      # Taker 费率 0.05%

# ============================================================
# 仓位 & 风控 — 0.5USDC / 20x 杠杆
# ============================================================
POSITION_SIZE_USDT = 5                  # 单笔名义价值 (USDT)，保证金 ~$0.25
MAX_POSITIONS = 1                       # 同时最大持仓数
MAX_DAILY_LOSS_USDT = 0.20              # 日亏损上限 (USDT)
MAX_DAILY_TRADES = 30                   # 日交易笔数上限

# ============================================================
# API 连接 — 2026 新架构
#   Public:  path 模式 ws (裸消息) — depth
#   Market:  stream 模式 ?streams= (包裹消息) — kline + forceOrder
# ============================================================
# 实盘
BINANCE_PUBLIC_WS = "wss://fstream.binance.com/public"
BINANCE_MARKET_WS = "wss://fstream.binance.com/market"
BINANCE_REST = "https://fapi.binance.com"
# 测试网
BINANCE_TESTNET_PUBLIC_WS = "wss://stream.binancefuture.com/public"
BINANCE_TESTNET_MARKET_WS = "wss://stream.binancefuture.com/market"
BINANCE_TESTNET_REST = "https://testnet.binancefuture.com"

USE_TESTNET = False                     # 实盘数据
PAPER_TRADE = False                      # 实盘下单

# API Key 从环境变量读取
# export BINANCE_API_KEY="your_key"
# export BINANCE_API_SECRET="your_secret"

# ============================================================
# 日志 & 持久化
# ============================================================
LOG_LEVEL = "INFO"
TRADE_DB_PATH = "trades.sqlite3"
HEARTBEAT_INTERVAL_SEC = 15            # 小账户心跳频繁一点
